"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      {/* Basic SEO Metadata */}
      <title>PropTrack | Home</title>
      <meta name="description" content="PropTrack is an integrated property management and tenant communication system." />
      <meta name="keywords" content="PropTrack, Property Management, Tenant System, Rental Management, Real Estate, Apartment Management" />
      <meta name="author" content="Your Name or Company Name" />

      {/* Favicon */}
      <link rel="icon" href="/favicon.ico" />
      </head>
    
      <body className={inter.className}>
        <SessionProvider>
            {children}
        </SessionProvider>
      </body>
    </html>
  );
}
