"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import {
  ClerkProvider,
  SignIn,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>PropTrack</title>
      </head>
      <body className={inter.className}>
        <SessionProvider>
            {children}
        </SessionProvider>
      </body>
    </html>
    // <ClerkProvider

    // >
    //   <html lang="en">
    //     <body className={inter.className}>
    //       <SignedOut>
    //         <SignIn
    //           appearance={{
    //             elements: {
    //               // Hide the "Sign Up" button/link
    //               formFieldAction__signUp: { display: 'none' },
    //               // Hide the entire footer (Secured by Clerk)
    //               cardFooter: { display: 'none' },
    //             },
    //           }}
    //         />
    //       </SignedOut>
    //       <SignedIn>
    //         <UserButton showName />
    //         {children}
    //       </SignedIn>
    //     </body>
    //   </html>
    // </ClerkProvider>
  );
}
